version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb

#  frontend:
#    build: ./frontend
#    container_name: frontend
#    ports:
#      - "4173:4173"
#    depends_on:
#      - backend
#
#  backend:
#    build: ./backend
#    container_name: backend
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mongodb

volumes:
  mongo-data:
